name: Vuepress Build

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: yarn install

      - name: Vuepress Build
        run: yarn build

      - name: Push Changes
        run: |
          git add .
          git commit -m "Build Successful"
          git push origin master
